// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mauboqbrmhmcmyhcrgan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdWJvcWJybWhtY215aGNyZ2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDgxMzUsImV4cCI6MjA2Nzc4NDEzNX0.r-FS-RyHYuf_I4ln-VAmVcWiHnbJILdMmKLFwXQSMVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});